name: Scala Tests

on:
  push:
    branchs:
      - master
  pull_request:
    branchs:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: sbt coverage test
      - name: Coverage Report
        run: sbt coverageReport